version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: yulia605/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/static
      - media_volume:/media
  frontend:
    image: yulia605/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static
  gateway:
    image: yulia605/kittygram_gateway
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/static
      - media_volume:/media
    ports:
      - 9000:80