version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/static
      - media:/media
  frontend:
    build: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: nginx:1.22.1
    ports:
      - 9000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/static
      - media:/media
